version: 2

workflows:
  version: 2
  package:
    jobs:
      - release:
          context: Master

jobs:
  release:
    docker:
      - image: "cimg/node:17.1.0"
    steps:
      - checkout
      - run:
          name: Copy package.json to ./dist for verification release
          command: mkdir -p ./dist && cp ./src/package.json ./dist/package.json
      - run:
          name: semantic release
          command: npm i semantic-release@18 @semantic-release/exec@6 && npx semantic-release || true
